### ISSUE TITLE
Try to dockerize/VMize everything

### ISSUE THREAD

**Issue by tuxology** [tuxology/tracevizlab#14]
We will try to install LTTng in a VM in a Docker container. Or maybe just a VM

- [ ] Ask LISA for resources. Access to DigitalOcean etc.

**Comment by PSRCode** [comment]
Please see this work from @jgalar:

https://github.com/jgalar/lttng-dockerfiles

**Comment by tuxology** [comment]
We won't have much time to generate traces after the first trial run, but we do have a VM with everything installed!
