### ISSUE TITLE
Why/when tracing

### ISSUE THREAD

**Issue by TheMatthew** [tuxology/tracevizlab#3]
Do we need this, what will be shown?

We need to have an example problem?

Not findable with debug or with profilers.

Link tracing with monitoring?
Link with logs?

**Comment by tuxology** [comment]
I am going to create introductory slides with something like this and give example of go/chrome tracing vs kernel tracing to highlight the difference. The introductory slides will cover the rationale behind the lab and tracing in general. For example, some diagrams like this to show where we stand

![image](https://user-images.githubusercontent.com/3373857/46979736-42856180-d087-11e8-8453-97b233d8d102.png)
