### ISSUE TITLE
404 for images and links

### ISSUE THREAD

**Issue by PSRCode** [tuxology/tracevizlab#44]
https://github.com/tuxology/tracevizlab/blob/master/labs/02-lttng-userspace-tracing/02-lttng-userspace-tracing.md#sub-task-4-memory-usage

Some link looks broken or imcomplete here:

https://github.com/tuxology/tracevizlab/blob/master/labs/02-lttng-userspace-tracing/screenshots/ustMemoryUsage.png

https://github.com/tuxology/tracevizlab/blob/master/labs/02-lttng-userspace-tracing/screenshots/ustMemoryPotentialLeaks.png

Feel free to close if this part is a work in progress.

**Comment by tahini** [comment]
Yes thanks for adding an issue, a lot of stuff was, and will be, renamed. We'll need to review every single link and screenshot towards the end.

And yeah, those screenshots have never been done yet...
